/*
 * Project name:
     NewDesign
 * Generated by:
     Visual TFT
 * Date of creation
     9/27/2013
 * Time of creation
     1:26:43 PM
 * Test configuration:
     MCU:             P33EP512MU810
     Dev.Board:       NewDesign0927
     Oscillator:      140000000 Hz
     SW:              mikroC PRO for DSPIC
                      http://www.mikroe.com/mikroc/dspic/
     Note:            Download FT800 library at
                      http://www.mikroe.com/visualtft/#ft800
                      Download (if using external memory storage) FAT32 library at
                      http://www.libstock.com/projects/view/108/fat32-library
 */

#include "NewDesign_objects.h"

void main() {
  InitVTFTStack();
  while (1) {
    ProcessVTFTStack();
  }

}
